### PR TITLE
fix(index): sanitize method name

### LINKED ISSUE #24: error fetching content via `post` (lowercase)
**Description**
```
async function testFetch() {
  const context = fetchAPI.context({
    // httpProtocol: 'http1',
    // httpsProtocols: ['http1'],
  });
  try {
    const resp = await context.fetch('https://httpbin.org/post', {
      method: 'post',
      headers: {
        accept: 'application/json',
      }
    });
    console.log(resp.status);
    const text = await resp.text();
    return {
      statusCode: 200,
      body: text,
    };
  } finally {
    await context.disconnectAll();
  }
}
```

produces:

```
Error [ERR_HTTP2_STREAM_ERROR]: Stream closed with error code NGHTTP2_PROTOCOL_ERROR
    at ClientHttp2Stream._destroy (internal/http2/core.js:2095:13)
    at ClientHttp2Stream.destroy (internal/streams/destroy.js:37:8)
    at ClientHttp2Stream.[kMaybeDestroy] (internal/http2/core.js:2111:12)
    at Http2Stream.onStreamClose [as onstreamclose] (internal/http2/core.js:479:26)
```

**Additional context**
after forcing http1, it works.

### PR DESCRIPTION
**Pull request by stefan-guggisberg**
fix #24

Please ensure your pull request adheres to the following guidelines:
- [ ] make sure to link the related issues in this description
- [ ] when merging / squashing, make sure the fixed issue references are visible in the commits, for easy compilation of release notes

## Related Issues

Thanks for contributing!

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -80,6 +80,12 @@ function createPushHandler(ctx) {
 
 const wrappedFetch = async (ctx, url, options = {}) => {
   const opts = { ...DEFAULT_FETCH_OPTIONS, ...options };
+  // sanitze method name (#24)
+  if (typeof opts.method === 'string') {
+    opts.method = opts.method.toUpperCase();
+  } else {
+    delete opts.method;
```
Comment (tripodsan) [inline src/index.js]: why delete ? wouldn't it be illegal to use a non-string method or undefined ?

Comment (stefan-guggisberg) [reply src/index.js]: I believe lowercase method names would also be illegal
