### PR TITLE
GH-234: fix TypeScript declarations

### LINKED ISSUE #234: TS7016: Could not find a declaration file for module './fetch/errors'
**Description**

TypeScript build generates "Could not find a declaration file for module './fetch/errors'" error when trying to build a project that uses `@adobe/helix-fetch`.

**To Reproduce**
```bash
npm init -y
npm i -D typescript @types/node
npm i @adobe/helix-fetch
```

tsconfig.js:
```json
{
  "compilerOptions": {
    "target": "es2016",
    "module": "commonjs",
    "esModuleInterop": true,
    "strict": true
  }
}
```

test.ts:
```typescript
import { fetch } from '@adobe/helix-fetch';
```

Run tsc:
```bash
npx tsc
```

**Expected behavior**
No errors reported

**Actual behavior**
```
node_modules/@adobe/helix-fetch/src/api.d.ts:13:29 - error TS7016: Could not find a declaration file for module './fetch/errors'. '/test/node_modules/@adobe/helix-fetch/src/fetch/errors.js' implicitly has an 'any' type.

13 import { SystemError } from "./fetch/errors";
                               ~~~~~~~~~~~~~~~~


Found 1 error.
```

**Version:**
run: `$ hlx --version`: `Command 'hlx' not found`

`npm ls @adobe/helix-fetch`: `@adobe/helix-fetch@3.0.0`

**Additional information**

When `tsc` sees `import { SystemError } from "./fetch/errors"`, it expects to find at `./fetch/errors.ts` or `./fetch/errors.d.ts`, but neither exists. Moreover, `SystemError` does not exist in `./fetch/errors.js`:

```
/test/node_modules/@adobe/helix-fetch/src$ grep class fetch/errors.js
/* eslint-disable max-classes-per-file */
class FetchBaseError extends Error {
class FetchError extends FetchBaseError {
class AbortError extends FetchBaseError {
```

### PR DESCRIPTION
**Pull request by sjinks**
Please ensure your pull request adheres to the following guidelines:
- [x] make sure to link the related issues in this description
- [x] when merging / squashing, make sure the fixed issue references are visible in the commits, for easy compilation of release notes

## Related Issues

#234

This PR fixes #234 by removing a reference to `./fetch/errors` in `api.d.ts` and providing a definition for the `SystemError` type (extracted from a JSDoc block of `fetch/errors.js`)

### CODE REVIEW

**Comment by sjinks** [comment]
Closing/reopening to trigger the CLA check.

File: src/api.d.ts [hunk 1]
```diff
@@ -281,6 +279,19 @@ export type AbortController = Window["window"]["AbortController"];
...
+  address?: string;
+  code: string;
+  dest?: string;
+  errno: number;
+  info?: object;
+  message: string;
+  path?: string;
+  port?: number;
+  syscall: string;
+}
```
Comment (sjinks) [inline src/api.d.ts:293]: Not sure if this interface should be exported.

**Review by stefan-guggisberg — APPROVED** [review]

**Comment by stefan-guggisberg** [comment]
Thanks for the PR!
