### PR TITLE
fix: preserve original req body and calculate content-length for non-stream body

### LINKED ISSUE #142: Unable to make POST requests with a POST body to Azure Functions API
Test case to follow

### PR DESCRIPTION
**Pull request by stefan-guggisberg**
fixes #142

### CODE REVIEW

File: src/core/request.js [hunk 1]
```diff
@@ -191,37 +193,57 @@ const request = async (ctx, uri, options) => {
...
+    contentType = 'application/x-www-form-urlencoded; charset=utf-8';
     opts.body = opts.body.toString();
+  } else if (opts.body instanceof FormData) {
+    contentType = `multipart/form-data;boundary=${opts.body.getBoundary()}`;
+    opts.body = opts.body.getBuffer();
   } else if (typeof opts.body === 'string' || opts.body instanceof String) {
-    if (!opts.headers['content-type']) {
-      opts.headers['content-type'] = 'text/plain; charset=utf-8';
-    }
+    contentType = 'text/plain; charset=utf-8';
```
Comment (trieloff) [inline src/core/request.js:215]: What if I want to post markdown or another text-based mime-type?

**Comment by trieloff** [comment]
Thank you!
